# Generated by Django 5.2.5 on 2025-08-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('dataNascita', models.DateField(blank=True, null=True)),
                ('dataMorte', models.DateField(blank=True, null=True)),
                ('nazionalita', models.CharField(blank=True, max_length=50)),
                ('stato', models.CharField(choices=[('vivo', 'Vivo'), ('morto', 'Morto')], default='vivo', help_text="Stato dell'artista", max_length=5)),
            ],
            options={
                'verbose_name': 'Autore',
                'verbose_name_plural': 'Autori',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie in metri quadrati', max_digits=7)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Sale',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temi',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('annoRealizzazione', models.IntegerField(blank=True, null=True)),
                ('annoAcquisto', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Quadro', 'Quadro'), ('Scultura', 'Scultura'), ('Non specificato', 'Non specificato')], default='Non specificato', max_length=20)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museo.autore', verbose_name="Autore dell'opera")),
                ('espostaInSala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museo.sala', verbose_name='Sala di esposizione')),
            ],
            options={
                'verbose_name': 'Opera',
                'verbose_name_plural': 'Opere',
                'ordering': ['titolo'],
            },
        ),
        migrations.AddField(
            model_name='sala',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museo.tema', verbose_name='Tema della sala'),
        ),
    ]
